version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    command: bun run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./contracts:/app/contracts
      - ./app:/app/app
      - ./dist:/app/dist
      - /app/node_modules
    networks:
      - thaink-network

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0
    ports:
      - "8545:8545"
    networks:
      - thaink-network

networks:
  thaink-network:
    driver: bridge
