[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['contracts/lib']
test = 'contracts/test'
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 200

# Test configuration
fuzz_runs = 256
invariant_runs = 256

# Remappings
remappings = [
    '@openzeppelin/=contracts/lib/openzeppelin-contracts/'
]