[profile.default]
src = 'contracts/src'
out = 'contracts/out'
script = 'contracts/scripts'
broadcast = 'contracts/broadcast'
cache_path = 'contracts/cache'
test = 'contracts/test'
libs = ['contracts/lib']
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 200

# Test configuration
fuzz_runs = 256
invariant_runs = 256

# Remappings
remappings = [
    '@openzeppelin/=contracts/lib/openzeppelin-contracts/'
]